### PR TITLE
Remove "Dropping unknown message..." log

### PR DESCRIPTION
**Pull request by TobiasWalle**
I removed the log which occurs if the message of the "message" event is unknown.
This can get pretty verbose if the library is used in combination with other libraries which are using the message event (For Example the webpack hot module replacement).

I also needed to update some of the dependencies, in order to get the tests to run smoothly.

Keep up the good work. I really like the approach of your library.

Regards
Tobias

### CODE REVIEW

**Comment by mreuvers** [comment]
Hey @TobiasWalle

Thank you for the pull request, makes sense to suppress this.

I am curious though why it didn't build for you originally? What kind of errors did you get?

**Comment by TobiasWalle** [comment]
Thank you @mreuvers 

The typescript compiler was complaining about the lodash typings. I think this was caused by an update the @types/lodash which was incompatible with the installed typescript version.
Because of the semantic versioning, we probably had different version of the dependencies.

I recommend using [yarn](https://yarnpkg.com/en/) instead of npm. Yarn creates an .lock file which prevents different versions on different machines. It is also way faster than npm.

**Comment by mreuvers** [comment]
Hello @TobiasWalle 

I see, my guess is you had typescript installed globally then or so (which I purposefully didn't install globally, since that changes/breaks so fast with newer versions atm).

Thanks for the link, I had a look at yarn and it looks interesting to try at some point. It seems like it's a wrapper on top of npm? Does that mean that all 'normal commands' still work with it? Specially I want for example 'publish' to remain working properly. :)

**Comment by TobiasWalle** [comment]
Hello @mreuvers 

Any command in npm scripts will use the local dependency before the global one. I not sure why I had a different version of typescript.

Yeah, it uses the same repository and some commands are just an wrapper for npm. I use it mostly for installing the local dependencies (`yarn install`) and to add or remove dependencies (`yarn add <package>` or `yarn add <package> --dev` etc.). What I really like is `yarn upgrade-interactive` which you can use to check the dependencies you want to upgrade.
For tasks like `npm publish` I still use npm, because yarn just wraps the functionality.

**Comment by mreuvers** [comment]
Ah I see thanks for explaining. I will check it out when I have some more time. It sounds useful. :)

**Pull request merged**
